Feature/show plot info
terragrids/dapp pull request #19
Opened 2022-08-02 06:30 UTC by masafumimori

- Add modal dialogue that shows image of tile, index, and coordinates when clicking a tile
- Remove unnecessary files (map.tsx, sample.tsx)

2022-08-02 07:21 UTC, lorenzopolidori requested changes

2022-08-02 07:21 UTC, lorenzopolidori commented on components/map/index.tsx
> +        if (!headerHeight) return
Maybe better `if (headerHeight === undefined)`? In theory, `headerHeight` could be 0.

2022-08-02 07:21 UTC, lorenzopolidori commented on components/map/tiles/tile-info-dialog.tsx
> +            title={'Selected tile infomation'}
Generally, english text should go in `strings/en.js`. I suggest we use "Terraland information" for now.

2022-08-02 07:21 UTC, lorenzopolidori commented on pages/index.js
> +// import Content from '../components/content'
I think we can remove this commented out line

2022-08-02 07:21 UTC, lorenzopolidori commented on pages/index.js
> +            />
We should change the map background colour to match the header background, i.e. `$color-mine-shaft: #242424`

2022-08-03 01:05 UTC, masafumimori commented on components/layout.js
> +                <meta property={'og:image'} content={''} />
yes this was due to Prettier. And this is related to `lineWidth` option I assume

2022-08-03 06:34 UTC, lorenzopolidori approved these changes

2022-08-03 06:34 UTC, merged