spp modal for desktop
terragrids/dapp pull request #31
Opened 2022-08-12 01:23 UTC by miryamfv

Shouldn't we make the modal responsive?

If so should have margin like in the mock on canvas or should it be wide as the screen like menu?

2022-08-12 08:34 UTC, lorenzopolidori requested changes

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +          <LoadingSpinner />
When the `LoadingSpinner` is visible, the dialog is much smaller, causing a UI glitch. Can we set the same size when it's loading the data?

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +          {/* TODO : change structure of html elements */}
Is this comment still valid?

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +          {/* <div className={styles.section}> */}
Can we remove this commented out line and the closing div tag below?

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +            {strings.capacity} $TRCS {solarPowerPlant.totalTrcl}
This should be:
```js
{strings.capacity} {solarPowerPlant.capacity} TRW
```

2022-08-12 08:34 UTC, lorenzopolidori commented on strings/en.js
> +  availableToBuy: 'Available',
`availableToBuy: 'Available to buy',`

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +          {/* <p>ACTIVE $TRCL {solarPowerPlant.activeTrcl}</p>So this is not needed anymore? */}
No, `solarPowerPlant.activeTrcl` is not displayed at the moment, but it is used to calculate the number of TRCL available to buy.

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.tsx
> +import LoadingSpinner from 'components/loading-spinner'
We should add `/* eslint-disable @next/next/no-img-element */` at the top of this file to avoid the eslint warning.

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.module.scss
> +.terracells {
Fro small screens, rather than shrinking the grid to become very small, we should re-arrange it to be displayed on less columns. For the smaller screens, it should be just one column.
I suggest:
```js
  @media (max-width: $screen-medium) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: $screen-small) {
    grid-template-columns: repeat(1, 1fr);
  }
```

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.module.scss
> +    footer {
The footer content (capacity and total output) should be displayed vertically for smaller screens, to make it easier to read.

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.module.scss
> +
For smaller screens, I would make the modal wider. In `modal-dialog.module.scss`, I would add:

```scss
.dialog {
   // ...
  @media (max-width: $screen-small) {
    max-width: none;
    width: 100%;
    margin: 0 15px;
    max-height: 95vh;
  }
}
```

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/solar-power-plant-dialog.module.scss
> +  // padding-bottom: 20px;
Can we remove this commented out line?

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/terracell-detail.tsx
> +  if (!terracell) return null
To display the Terracell details, we need to fetch them from `endpoint.nft(terracellId)`. This will return more information about the individual terracell, such as the owner address.

2022-08-12 08:34 UTC, lorenzopolidori commented on components/solar-power-plant/terracell-detail.module.scss
> +
This layout should be fixed for smaller screens. I suggest we arrange this vertically, with the image at the top and the details below the image.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/2437709/184314040-eeb6456c-61e8-4838-bbb2-0be5806c9a49.png">

2022-08-12 11:56 UTC, masafumimori commented on .prettierrc.json
> +    "tabWidth": 2,
I'm sorry! This was because the code you have created before (and/or recently) looked like having tab-width 2 so I thought it'd be good to adjust to your config. (This is also the reason for setting the default formatter change)

2022-08-12 11:56 UTC, masafumimori commented on .vscode/settings.json
> +}
I thought the formatters were mixed among us (ie. tab width), so I thought it would be better to set Prettier ext for the default formatter.

As for making new lines of array/object, it is more related to Prettier `lineWidth` setting which should be set as `120` now.
But to make it flexible. I think we need to use `// prettier-ignore` or eslint config, both mentioned [here](https://github.com/prettier/prettier-vscode/issues/352)

2022-08-12 12:19 UTC, masafumimori commented on components/solar-power-plant/terracell-detail.tsx
> +  if (!terracell) return null
Can I work on this on the task for Terracell detail?(https://trello.com/c/V3HU2ou1/6-show-available-terracells-in-the-solar-power-plant)

2022-08-12 12:19 UTC, masafumimori commented on components/solar-power-plant/terracell-detail.module.scss
> +
Can I work on this on the task for Terracell detail?(https://trello.com/c/V3HU2ou1/6-show-available-terracells-in-the-solar-power-plant)

2022-08-13 10:28 UTC, masafumimori commented on components/button.module.scss
> +.default {
I wasnt sure if I put `width: 100%` in `button.module.scss` as button style so I add that property under `.buttonWrapper` in `terracell-detail.module.scss` file

2022-08-14 08:01 UTC, lorenzopolidori approved these changes

2022-08-14 08:01 UTC, merged