Feature/stateless auth
terragrids/dapp pull request #50
Opened 2022-10-12 06:18 UTC by cyleecode

2022-10-13 21:55 UTC, lorenzopolidori requested changes

2022-10-13 21:55 UTC, lorenzopolidori commented on components/wallet-picker.js
> +        const notePlainText = `https://testnet.terragrids.org/ ${Date.now() + 86400000}`
This URL should depend on the environment. 
I suggest returning the app URL in a function in `string-utils.js`, similar to `getApplicationAlgoExplorerUrl`.

2022-10-13 21:55 UTC, lorenzopolidori commented on components/wallet-picker.js
> +        const signedTxns = await window.algorand.signTxns(txnToSign) //ARCs14
When I connect to a MyAlgo wallet, this function returns the signed transaction. However, when I connect with a Pera Wallet on a mobile device, this function never returns and the wallet do not prompt me to sign the transaction.

2022-10-17 14:04 UTC, cyleecode commented on components/wallet-picker.js
> +        const notePlainText = `https://testnet.terragrids.org/ ${Date.now() + 86400000}`
Added function in https://github.com/terragrids/dapp/commit/186f15bbd0a6fa092a178449426d8cc29da6cd29

2022-10-17 20:45 UTC, lorenzopolidori commented on utils/string-utils.js
> +    const prefix = process.env.NEXT_PUBLIC_REACH_CONSENSUS_NETWORK_PROVIDER === 'TestNet' ? 'testnet.' : 'app'
`'testnet' : 'app'`

2022-10-17 20:45 UTC, lorenzopolidori commented on utils/string-utils.js
> +    return `https://${prefix}terragrids.org/`
``return  `https://${prefix}.terragrids.org/` ``

2022-10-17 20:49 UTC, lorenzopolidori commented on components/wallet-picker.js
> +        await statelessAuthenticate()
I think we can remove `statelessAuthenticate()` from `connectMyAlgoWallet()` and `connectPeraWallet()` for now, to avoid having to sign a 0-fee transaction after connecting. Most of the app is accessible without authentication (e.g. fetching data is generally public), so we should ask for authentication only when needed, e.g. before posting data to the backend or retrieving personal data for a user.

2022-10-22 15:39 UTC, lorenzopolidori approved these changes

2022-10-22 15:39 UTC, merged